name: Build and save my Docker image to a registry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "exo.container-registry.com" # Nom du registre sans "azurecr.io"
  IMAGE_NAME: "backend-app" # Nom de votre image dans acr

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      #ajouter les étapes pour build votre image docker et la pousser sur la registry donnée
      - name: connection à la repository
        run: |
          docker login -u quentin.badoud@edufr.ch -p ${{ secrets.DOCKER_PASSWORD }} $REG_NAME
      
      - name: build docker image
        run: |
          cd src/backend
          docker build -t ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }} .


      - name: tag docker image
        run: |
          docker tag ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }} ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }}:toa


      - name: push sur la registry
        run: |
          docker push ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }}:toa